### ISSUE TITLE
[Android] Error load file on Android

### ISSUE THREAD

**Issue by nhnpro** [yuyang9119/UnityAssetStoreSupport#1]
Can not find localization folder on android:
Error Log:
DirectoryNotFoundException: Could not find a part of the path "/jar:file:/..."

I already build the binary files into StreamingAsset folder!

**Comment by YT-GameMaker** [comment]
I just read the documentation of `Application.streamingAssetsPath` and found this:

> It is not possible to access the StreamingAssets folder on WebGL and Android platforms. No file access is available on WebGL. Android uses a compressed .apk file. These platforms return a URL. Use the UnityWebRequest class to access the Assets.

I'll fix this issue and publish a new version, please notice the notification from asset store.

**Comment by nhnpro** [comment]
Yes I know, you should use UnityWebRequest to access StreamingAssets folder on Android/WebGL platform! Your asset is really good, thank you so much! It will better if it can read the source from the GoogleSheet and live update ^_^.
