### ISSUE TITLE
如果我想在Tween里添加两个相同的组件，作用目标也是同个物体的时候运行起来效果总是错的

### ISSUE THREAD

**Issue by Mdtcy** [yuyang9119/UnityAssetStoreSupport#11]
例如那个改变颜色我想先从A颜色到B,再从B颜色到C就不行

**Comment by YT-GameMaker** [comment]
您可以通过设置 Time Range 来让不同组件工作在不同时间段，设置 Time Range 时注意同时设置起止的 Hold 状态，Hold 的意思是，在工作时间范围之外是否维持开始或结束的状态。

**Comment by Mdtcy** [comment]
没问题了，之前我没设置好hold
