### ISSUE TITLE
Feature Request: Select Target

### ISSUE THREAD

**Issue by marcusx2** [yuyang9119/UnityAssetStoreSupport#12]
It would be nice being able to animate a target other than the gameobject which the tweenplayer is currently attached to. In DoTweenPro I can easily select another target other than self in the inspector.

**Comment by YT-GameMaker** [comment]
Yes you can select another target in TweenPlayer!

**Comment by marcusx2** [comment]
How?
EDIT
Oh I found out. Wonderful!

@yuyang9119 I updated my review on the store! Excellent work with this asset!
