### ISSUE TITLE
Fill Amount 和 Graphic Color 不能在Editor模式下刷新

### ISSUE THREAD

**Issue by xxl-game** [yuyang9119/UnityAssetStoreSupport#14]
在运行状态下是正常的。
在编辑器状态下，Inspector 面板数据是在变化的，但无论是 Game 视图还是 Scene 视图，画面都没有变化，需要手动拖动 Game 视图窗体大小时，才能看到动画的预览。

我后来又尝试了 Dotween 发现也有这个问题，这个有办法可以解决吗？还是说由于 Unity 系统的原因没法做到？

**Comment by xxl-game** [comment]
我试了下这样搞，可以在非运行状态下预览动画了，但是不知道会不会有什么问题。

```
if (target)
{
    target.color = value;
#if UNITY_EDITOR
    if (!Application.isPlaying)
    {
        EditorUtility.SetDirty(target);
    }
#endif
}
```

**Comment by YT-GameMaker** [comment]
这个是因为 Unity UI 实现的问题，暂时没有好的结局办法。

**Comment by xxl-game** [comment]
> 这个是因为 Unity UI 实现的问题，暂时没有好的结局办法。

我那个修改的办法你看了吗，我感觉没啥问题。

**Comment by YT-GameMaker** [comment]
之前好像试过，不太可靠，就移除了……之后我再看看这个问题。
