### ISSUE TITLE
More intepolator options

### ISSUE THREAD

**Issue by marcusx2** [yuyang9119/UnityAssetStoreSupport#17]
Please see [https://easings.net/](https://easings.net/). DOTweenPRO supports all of these interpolators. It would be nice if Tween Player supported them too out of the box.

**Comment by YT-GameMaker** [comment]
Most interpolators in TweenPlayer are adjustable, click LMB to drag redline in  interpolator editor.

**Comment by marcusx2** [comment]
I know that, but more out of the box options would be nice.
