### ISSUE TITLE
Save System documentation?

### ISSUE THREAD

**Issue by JesseTG** [yuyang9119/UnityAssetStoreSupport#2]
Is the documentation for your [Save System](https://assetstore.unity.com/packages/tools/integration/save-system-158923) asset available anywhere? I'd like to read through it to decide if it would be a good fit for my game.

**Comment by YT-GameMaker** [comment]
This is ReadMe file inside the package:
[README.pdf](https://github.com/yuyang9119/UnityAssetStoreSupport/files/4240659/README.pdf)

**Comment by JesseTG** [comment]
Thank you, I appreciate it.
