### ISSUE TITLE
How can I tween the color of a text using the Tween Player asset?

### ISSUE THREAD

**Issue by marcusx2** [yuyang9119/UnityAssetStoreSupport#20]
Title says it all. Specifically, I'm trying to make the text fade in and fade out. I can't get it to work, I tried using the "graphic color" option, but it makes the text suddenly disappear at the end of the tween instead of slowly fading away.

**Comment by marcusx2** [comment]
It seems that there is no support to change the color of a text?

**Comment by YT-GameMaker** [comment]
You can use Tween Graphic Color, the problem you mentioned is actually a problem with edit-mode, It's OK in play-mode.
