### ISSUE TITLE
tween player - no way to loop x amount of times?

### ISSUE THREAD

**Issue by marcusx2** [yuyang9119/UnityAssetStoreSupport#21]
I can select the tween to loop or ping pong, which is great. But I can't select how many times. What if I don't want to do it infinitely? Please add the option to let the user control how many times he wants to loop or ping pong.

**Comment by YT-GameMaker** [comment]
You can use custom interpolator instead, like this:
![image](https://user-images.githubusercontent.com/18855621/151491207-320aa59c-1fd4-431e-ab9e-da5a2b5f6360.png)
