### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MouradZzz** [yuyang9119/UnityAssetStoreSupport#3]
![d](https://user-images.githubusercontent.com/55241681/75112663-1e0ba300-5646-11ea-8144-dec388ee51ad.PNG)

Hi, I'm trying to do the same setup of your scene MutiSave, but I have a problem can you help me?

**Comment by YT-GameMaker** [comment]
It is a null reference issue, usually it happends if you forget to initialize variable. Could you find out the variable or send me a sample?

**Comment by MouradZzz** [comment]
![sf](https://user-images.githubusercontent.com/55241681/75112973-92941100-5649-11ea-8f7f-9f5c1c2883f8.PNG)
I don't if is gonna help you

**Comment by MouradZzz** [comment]
![greg](https://user-images.githubusercontent.com/55241681/75113000-d0913500-5649-11ea-86a9-87d8cea60e64.PNG)
The setup in a player like yours scene

**Comment by YT-GameMaker** [comment]
it looks like the `s` in `s.Reset()` is null, if you had already init the `SaveRegistry` with the instance of Player, the problem might be error execution order, the `instance` of Player is not initialized before create the `SaveRegistry`.
