### ISSUE TITLE
你好！TweenPlayer的扩展UI动画界面可以结合Sirenix.OdinInspector吗？使用OnInspectorGUI函数里写比较麻烦。

### ISSUE THREAD

**Issue by o2co2** [yuyang9119/UnityAssetStoreSupport#4]
你好！TweenPlayer的扩展UI动画界面可以结合Sirenix.OdinInspector吗？使用OnInspectorGUI函数里写比较麻烦。
谢谢

**Comment by o2co2** [comment]
刚买了你的TweenPlayer插件

**Comment by YT-GameMaker** [comment]
是说，希望使用 OdinInspector API 绘制编辑器界面？如果是这个意思，恐怕是不可以的，因为那是别人的插件，我不能依赖它。
实际上，现在实现扩展非常简单，大部分情况下不需要写任何编辑器代码，如果需要显示额外的数据，可以参考插件内置的一些实现。

**Comment by o2co2** [comment]
如果使用OdinInspector 显示额外的数据UI就非常方便，或者说有没有办法做到？我好去尝试

**Comment by o2co2** [comment]
我试了一下午  还没找到方法

**Comment by YT-GameMaker** [comment]
抱歉，我不了解odin的原理，你可以看看odin的文档。

**Comment by o2co2** [comment]
是否可以添加  Unity Visual Effect Graph 参数动画的功能？  这个是我需要的  谢谢

**Comment by YT-GameMaker** [comment]
VEG 我暂时还不了解，不过我会看一下的，如果合适我会加上的，感谢反馈。
如果您现在急需，也可以先试试自行扩展。
