### ISSUE TITLE
[Request] Allow for tween player profiles using scriptable objects

### ISSUE THREAD

**Issue by crystalbyte** [yuyang9119/UnityAssetStoreSupport#8]
Hi,

I have recently bought the component and I would like to request the option to have profiles using ScriptableObjects to assign to tween animations in order to have a centralized configuration which can be assigned across scenes. Currently we have to change multiple durations when we decide to change it across different players.

**Comment by YT-GameMaker** [comment]
Hi, sorry for late replying. ScriptableObjects make things complicate, you can use prefabs (with overrides) instead.

**Comment by xxl-game** [comment]
> you can use prefabs (with overrides) instead.

I would like to request the option too.
I can use prefabs to share on mutiple instances, but what can i do if i want to share TweenPlayer settings on multiple different prefabs. I do have that need. Can you offer the profiles option? Then i can decide whether to use it or not according to the different demand.
