### ISSUE TITLE
怎么让它旋转的时候使用当前的角度？from当前的值

### ISSUE THREAD

**Issue by Mdtcy** [yuyang9119/UnityAssetStoreSupport#9]

**Comment by YT-GameMaker** [comment]
可以调用 TweenPlayer.GetAnimation().LetFromEqualCurrent() 方法。

**Comment by xxl-game** [comment]
> 可以调用 TweenPlayer.GetAnimation().LetFromEqualCurrent() 方法。

这个可以直接集成在TweenPlayer的Inspector里设置吗，我们想把动画直接交给美术完成，不需要程序写代码。

**Comment by YT-GameMaker** [comment]
> > 可以调用 TweenPlayer.GetAnimation().LetFromEqualCurrent() 方法。
> 
> 这个可以直接集成在TweenPlayer的Inspector里设置吗，我们想把动画直接交给美术完成，不需要程序写代码。

可以点击每个动画右上角的菜单，图标是三个点，里面有这个命令。TweenPlayer整体右上角也有类似的菜单。

**Comment by xxl-game** [comment]
> 可以点击每个动画右上角的菜单，图标是三个点，里面有这个命令。TweenPlayer整体右上角也有类似的菜单。

我指的是使用运行时的当前值，不是编辑器下的当前值。也就是 DoTween 里的 Relative 功能。考虑一个需求，我有10个位置不同的 Cube，需要让他们每个都往前运动 5，目前版本这个需求应该是没法重用同一个动画的。

**Comment by YT-GameMaker** [comment]
> > 可以点击每个动画右上角的菜单，图标是三个点，里面有这个命令。TweenPlayer整体右上角也有类似的菜单。
> 
> 我指的是使用运行时的当前值，不是编辑器下的当前值。也就是 DoTween 里的 Relative 功能。考虑一个需求，我有10个位置不同的 Cube，需要让他们每个都往前运动 5，目前版本这个需求应该是没法重用同一个动画的。

这个需求我后续更新时考虑一下，目前可以将动画物体添加一个parent，然后设置动画物体设置为 Local Space 作为替代方案。
